//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dkim.Evaluator.Rules
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DKimEvaluatorRulesResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DKimEvaluatorRulesResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Dkim.Evaluator.Rules.DKimEvaluatorRulesResources", typeof(DKimEvaluatorRulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }


        
        /// <summary>
        ///   Looks up a localized string similar to The selector has been revoked
        /// </summary>
        public static string NullPublicKeyConfigured
        {
            get
            {
                return ResourceManager.GetString("NullPublicKeyConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector is incorrectly configured..
        /// </summary>
        public static string IncorrectPublicKeyConfigured
        {
            get
            {
                return ResourceManager.GetString("IncorrectPublicKeyConfigured", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record must contain a public key data tag..
        /// </summary>
        public static string PublicKeyDataTagMustExistErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PublicKeyDataTagMustExistErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The public rsa key is too short, key size {0}..
        /// </summary>
        public static string PublicKeyIsToShortErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PublicKeyIsToShortErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The public rsa key is too short, key size {0} - Use a longer key size &gt;= 2048..
        /// </summary>
        public static string PublicKeyIsToShortUseLongerErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PublicKeyIsToShortUseLongerErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record must contain a public key type tag..
        /// </summary>
        public static string PublicKeyTypeTagMustExistErrorMessage
        {
            get
            {
                return ResourceManager.GetString("PublicKeyTypeTagMustExistErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to the public key could not be decoded.
        /// </summary>
        public static string CorruptPublicKeyErrorMessage
        {
            get
            {
                return ResourceManager.GetString("CorruptPublicKeyErrorMessage", resourceCulture);
            }
        }
    }
}
