//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dkim.Evaluator.Parsers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DKimEvaluatorParsersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DKimEvaluatorParsersResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Dkim.Evaluator.Parsers.DKimEvaluatorParsersResources", typeof(DKimEvaluatorParsersResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for flag type. Valid values are y and s..
        /// </summary>
        public static string InvalidFlagTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidFlagTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for t (flags tag). Flags should be a colon-separated list and can contain the following values: y, s.
        /// </summary>
        public static string InvalidFlagValueErrorMessage {
            get {
                return ResourceManager.GetString("InvalidFlagValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for h (hash algorithm tag). Hash algorithm should be a colon-separated list and can contain the following values: sha1, sha256.
        /// </summary>
        public static string InvalidHashAlgorithmErrorMessage {
            get {
                return ResourceManager.GetString("InvalidHashAlgorithmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for p (public key data tag). Value must be a base64 string..
        /// </summary>
        public static string InvalidPublicKeyErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPublicKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for k (public key type) tag. Valid values are rsa or ed25519..
        /// </summary>
        public static string InvalidPublicTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPublicTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for s (service type) tag. Valid values are email or *..
        /// </summary>
        public static string InvalidServiceTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidServiceTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for v (version) tag. Value should be DKIM1..
        /// </summary>
        public static string InvalidVersionErrorMessage {
            get {
                return ResourceManager.GetString("InvalidVersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. The {1} tag should occur no more than {2}. This record has {3} occurrences..
        /// </summary>
        public static string MoreThanMaxOccursErrorMessage {
            get {
                return ResourceManager.GetString("MoreThanMaxOccursErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. {1}..
        /// </summary>
        public static string NoteMessage {
            get {
                return ResourceManager.GetString("NoteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Record must contain a public key data tag..
        /// </summary>
        public static string PublicKeyDataTagMustExistErrorMessage {
            get {
                return ResourceManager.GetString("PublicKeyDataTagMustExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected values {0} in {1} {2}..
        /// </summary>
        public static string UnexpectedValueErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedValueErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Invalid value &apos;{1}&apos; for hash algorithm. Valid values are sha1 and sha256..
        /// </summary>
        public static string UnknownHashAlgorithmErrorMessage {
            get {
                return ResourceManager.GetString("UnknownHashAlgorithmErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector {0}. Unknown tag {1} with value {2}..
        /// </summary>
        public static string UnknownTagErrorMessage {
            get {
                return ResourceManager.GetString("UnknownTagErrorMessage", resourceCulture);
            }
        }
    }
}
