//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Dkim.Evaluator.Parsers {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DKimEvaluatorParsersMarkdownResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DKimEvaluatorParsersMarkdownResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.Dkim.Evaluator.Parsers.DKimEvaluatorParsersMarkdownResources", typeof(DKimEvaluatorParsersMarkdownResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string InvalidFlagTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidFlagTypeErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidFlagValueErrorMessage {
            get {
                return ResourceManager.GetString("InvalidFlagValueErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidHashAlgorithmErrorMessage {
            get {
                return ResourceManager.GetString("InvalidHashAlgorithmErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidPublicKeyErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPublicKeyErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidPublicTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidPublicTypeErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidServiceTypeErrorMessage {
            get {
                return ResourceManager.GetString("InvalidServiceTypeErrorMessage", resourceCulture);
            }
        }
        
        public static string InvalidVersionErrorMessage {
            get {
                return ResourceManager.GetString("InvalidVersionErrorMessage", resourceCulture);
            }
        }
        
        public static string MoreThanMaxOccursErrorMessage {
            get {
                return ResourceManager.GetString("MoreThanMaxOccursErrorMessage", resourceCulture);
            }
        }
        
        public static string PublicKeyDataTagMustExistErrorMessage {
            get {
                return ResourceManager.GetString("PublicKeyDataTagMustExistErrorMessage", resourceCulture);
            }
        }
        
        public static string PublicKeyTypeTagMustExistErrorMessage {
            get {
                return ResourceManager.GetString("PublicKeyTypeTagMustExistErrorMessage", resourceCulture);
            }
        }
        
        public static string UnexpectedValueErrorMessage {
            get {
                return ResourceManager.GetString("UnexpectedValueErrorMessage", resourceCulture);
            }
        }
        
        public static string UnknownHashAlgorithmErrorMessage {
            get {
                return ResourceManager.GetString("UnknownHashAlgorithmErrorMessage", resourceCulture);
            }
        }
        
        public static string UnknownTagErrorMessage {
            get {
                return ResourceManager.GetString("UnknownTagErrorMessage", resourceCulture);
            }
        }
    }
}
